"""add contact inquiries table

Revision ID: 03ca36b7af8b
Revises: add_tuition_admissions
Create Date: 2025-11-16 18:48:50.122932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03ca36b7af8b'
down_revision = 'add_tuition_admissions'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('inquiry_type', sa.Enum('HIGHER_EDUCATION', 'SCHOLARSHIP_ORGANIZATION', 'OTHER', name='inquirytype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_inquiries_id'), 'contact_inquiries', ['id'], unique=False)
    op.alter_column('admissions_data', 'institution_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('admissions_data', 'is_admin_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_admissions_data_academic_year', table_name='admissions_data')
    op.drop_index('ix_admissions_data_acceptance_rate', table_name='admissions_data')
    op.drop_constraint('uq_admissions_institution_year', 'admissions_data', type_='unique')
    op.drop_constraint('admissions_data_last_updated_by_fkey', 'admissions_data', type_='foreignkey')
    op.drop_column('admissions_data', 'last_updated_by')
    op.drop_column('admissions_data', 'updated_at')
    op.drop_column('admissions_data', 'admin_notes')
    op.alter_column('tuition_data', 'institution_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tuition_data', 'data_source',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('tuition_data', 'tuition_in_state',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('tuition_data', 'tuition_out_state',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('tuition_data', 'required_fees_in_state',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('tuition_data', 'required_fees_out_state',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('tuition_data', 'room_board_on_campus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('tuition_data', 'is_admin_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_tuition_data_academic_year', table_name='tuition_data')
    op.drop_constraint('uq_tuition_institution_year_source', 'tuition_data', type_='unique')
    op.drop_constraint('tuition_data_last_updated_by_fkey', 'tuition_data', type_='foreignkey')
    op.drop_column('tuition_data', 'last_updated_by')
    op.drop_column('tuition_data', 'admin_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tuition_data', sa.Column('admin_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tuition_data', sa.Column('last_updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tuition_data_last_updated_by_fkey', 'tuition_data', 'admin_users', ['last_updated_by'], ['id'])
    op.create_unique_constraint('uq_tuition_institution_year_source', 'tuition_data', ['ipeds_id', 'academic_year', 'data_source'])
    op.create_index('ix_tuition_data_academic_year', 'tuition_data', ['academic_year'], unique=False)
    op.alter_column('tuition_data', 'is_admin_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tuition_data', 'room_board_on_campus',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('tuition_data', 'required_fees_out_state',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('tuition_data', 'required_fees_in_state',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('tuition_data', 'tuition_out_state',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('tuition_data', 'tuition_in_state',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('tuition_data', 'data_source',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('tuition_data', 'institution_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('admissions_data', sa.Column('admin_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('admissions_data', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('admissions_data', sa.Column('last_updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('admissions_data_last_updated_by_fkey', 'admissions_data', 'admin_users', ['last_updated_by'], ['id'])
    op.create_unique_constraint('uq_admissions_institution_year', 'admissions_data', ['ipeds_id', 'academic_year'])
    op.create_index('ix_admissions_data_acceptance_rate', 'admissions_data', ['acceptance_rate'], unique=False)
    op.create_index('ix_admissions_data_academic_year', 'admissions_data', ['academic_year'], unique=False)
    op.alter_column('admissions_data', 'is_admin_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('admissions_data', 'institution_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_contact_inquiries_id'), table_name='contact_inquiries')
    op.drop_table('contact_inquiries')
    # ### end Alembic commands ###
