"""add institution data verifications table

Revision ID: 5a76b93eb368
Revises: eb62ecd1447b
Create Date: 2025-11-26 05:46:45.808276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a76b93eb368'
down_revision = 'eb62ecd1447b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_data_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.String(length=255), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_data_verifications_id'), 'institution_data_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_institution_data_verifications_institution_id'), 'institution_data_verifications', ['institution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institution_data_verifications_institution_id'), table_name='institution_data_verifications')
    op.drop_index(op.f('ix_institution_data_verifications_id'), table_name='institution_data_verifications')
    op.drop_table('institution_data_verifications')
    # ### end Alembic commands ###
