"""creating super admin user account

Revision ID: 917197b7ae12
Revises: gallery_videos_001
Create Date: 2025-11-15 08:03:27.398613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '917197b7ae12'
down_revision = 'gallery_videos_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('assigned_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CLAIMED', 'EXPIRED', name='invitationstatus'), nullable=False),
    sa.Column('claimed_by', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitation_codes_code'), 'invitation_codes', ['code'], unique=True)
    op.create_index(op.f('ix_invitation_codes_entity_id'), 'invitation_codes', ['entity_id'], unique=False)
    op.create_index(op.f('ix_invitation_codes_id'), 'invitation_codes', ['id'], unique=False)
    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('conversion_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_templates_id'), 'message_templates', ['id'], unique=False)
    op.create_table('outreach_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outreach_tracking_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('contact_method', sa.String(length=50), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('message_sent', sa.Text(), nullable=True),
    sa.Column('response_received', sa.Boolean(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('response_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_activities_id'), 'outreach_activities', ['id'], unique=False)
    op.create_index(op.f('ix_outreach_activities_outreach_tracking_id'), 'outreach_activities', ['outreach_tracking_id'], unique=False)
    op.create_table('outreach_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_title', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('NOT_CONTACTED', 'CONTACTED', 'FOLLOW_UP_SENT', 'REGISTERED', 'DECLINED', 'NO_RESPONSE', name='contactstatus'), nullable=False),
    sa.Column('last_contact_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_contact_method', sa.Enum('EMAIL', 'LINKEDIN', 'PHONE', 'TEXT', 'OTHER', name='contactmethod'), nullable=True),
    sa.Column('contact_attempt_count', sa.Integer(), nullable=True),
    sa.Column('invitation_code_id', sa.Integer(), nullable=True),
    sa.Column('invitation_sent_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('next_follow_up_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('follow_up_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('response_feedback', sa.Text(), nullable=True),
    sa.Column('registered_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('registered_admin_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['invitation_code_id'], ['invitation_codes.id'], ),
    sa.ForeignKeyConstraint(['registered_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_tracking_entity_id'), 'outreach_tracking', ['entity_id'], unique=False)
    op.create_index(op.f('ix_outreach_tracking_id'), 'outreach_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_outreach_tracking_status'), 'outreach_tracking', ['status'], unique=False)
    op.drop_index('ix_institution_videos_display_order', table_name='institution_videos')
    op.drop_index('ix_institution_videos_institution_id', table_name='institution_videos')
    op.drop_table('institution_videos')
    op.drop_index('ix_institution_extended_info_institution_id', table_name='institution_extended_info')
    op.drop_table('institution_extended_info')
    op.drop_index('ix_institution_images_display_order', table_name='institution_images')
    op.drop_index('ix_institution_images_institution_id', table_name='institution_images')
    op.drop_table('institution_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('institution_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('cdn_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('caption', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_featured', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('image_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name='institution_images_institution_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='institution_images_pkey')
    )
    op.create_index('ix_institution_images_institution_id', 'institution_images', ['institution_id'], unique=False)
    op.create_index('ix_institution_images_display_order', 'institution_images', ['display_order'], unique=False)
    op.create_table('institution_extended_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('institution_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('campus_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('student_life', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('housing_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dining_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('programs_overview', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('faculty_highlights', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('research_opportunities', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('study_abroad', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('application_tips', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('financial_aid_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scholarship_opportunities', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('athletics_overview', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('clubs_organizations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_highlights', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('facilities_overview', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('custom_sections', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name='institution_extended_info_institution_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='institution_extended_info_pkey'),
    sa.UniqueConstraint('institution_id', name='institution_extended_info_institution_id_key')
    )
    op.create_index('ix_institution_extended_info_institution_id', 'institution_extended_info', ['institution_id'], unique=False)
    op.create_table('institution_videos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('institution_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('thumbnail_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('video_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_featured', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name='institution_videos_institution_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='institution_videos_pkey')
    )
    op.create_index('ix_institution_videos_institution_id', 'institution_videos', ['institution_id'], unique=False)
    op.create_index('ix_institution_videos_display_order', 'institution_videos', ['display_order'], unique=False)
    op.drop_index(op.f('ix_outreach_tracking_status'), table_name='outreach_tracking')
    op.drop_index(op.f('ix_outreach_tracking_id'), table_name='outreach_tracking')
    op.drop_index(op.f('ix_outreach_tracking_entity_id'), table_name='outreach_tracking')
    op.drop_table('outreach_tracking')
    op.drop_index(op.f('ix_outreach_activities_outreach_tracking_id'), table_name='outreach_activities')
    op.drop_index(op.f('ix_outreach_activities_id'), table_name='outreach_activities')
    op.drop_table('outreach_activities')
    op.drop_index(op.f('ix_message_templates_id'), table_name='message_templates')
    op.drop_table('message_templates')
    op.drop_index(op.f('ix_invitation_codes_id'), table_name='invitation_codes')
    op.drop_index(op.f('ix_invitation_codes_entity_id'), table_name='invitation_codes')
    op.drop_index(op.f('ix_invitation_codes_code'), table_name='invitation_codes')
    op.drop_table('invitation_codes')
    # ### end Alembic commands ###
