"""campusconnect_initial_admin_tables

Revision ID: c7627ac90d7f
Revises: 
Create Date: 2025-11-22 08:38:18.052102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7627ac90d7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_extended_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('campus_description', sa.Text(), nullable=True),
    sa.Column('student_life', sa.Text(), nullable=True),
    sa.Column('housing_info', sa.Text(), nullable=True),
    sa.Column('dining_info', sa.Text(), nullable=True),
    sa.Column('programs_overview', sa.Text(), nullable=True),
    sa.Column('faculty_highlights', sa.Text(), nullable=True),
    sa.Column('research_opportunities', sa.Text(), nullable=True),
    sa.Column('study_abroad', sa.Text(), nullable=True),
    sa.Column('application_tips', sa.Text(), nullable=True),
    sa.Column('financial_aid_info', sa.Text(), nullable=True),
    sa.Column('scholarship_opportunities', sa.Text(), nullable=True),
    sa.Column('athletics_overview', sa.Text(), nullable=True),
    sa.Column('clubs_organizations', sa.Text(), nullable=True),
    sa.Column('location_highlights', sa.Text(), nullable=True),
    sa.Column('facilities_overview', sa.Text(), nullable=True),
    sa.Column('custom_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_extended_info_id'), 'institution_extended_info', ['id'], unique=False)
    op.create_index(op.f('ix_institution_extended_info_institution_id'), 'institution_extended_info', ['institution_id'], unique=True)
    op.create_table('institution_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('cdn_url', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_images_display_order'), 'institution_images', ['display_order'], unique=False)
    op.create_index(op.f('ix_institution_images_id'), 'institution_images', ['id'], unique=False)
    op.create_index(op.f('ix_institution_images_institution_id'), 'institution_images', ['institution_id'], unique=False)
    op.create_table('institution_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('video_type', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_videos_display_order'), 'institution_videos', ['display_order'], unique=False)
    op.create_index(op.f('ix_institution_videos_id'), 'institution_videos', ['id'], unique=False)
    op.create_index(op.f('ix_institution_videos_institution_id'), 'institution_videos', ['institution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institution_videos_institution_id'), table_name='institution_videos')
    op.drop_index(op.f('ix_institution_videos_id'), table_name='institution_videos')
    op.drop_index(op.f('ix_institution_videos_display_order'), table_name='institution_videos')
    op.drop_table('institution_videos')
    op.drop_index(op.f('ix_institution_images_institution_id'), table_name='institution_images')
    op.drop_index(op.f('ix_institution_images_id'), table_name='institution_images')
    op.drop_index(op.f('ix_institution_images_display_order'), table_name='institution_images')
    op.drop_table('institution_images')
    op.drop_index(op.f('ix_institution_extended_info_institution_id'), table_name='institution_extended_info')
    op.drop_index(op.f('ix_institution_extended_info_id'), table_name='institution_extended_info')
    op.drop_table('institution_extended_info')
    # ### end Alembic commands ###
