"""Initial schema with correct enum values

Revision ID: d4e6bce4ebdf
Revises: 
Create Date: 2025-11-14 04:51:44.446306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e6bce4ebdf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_table('display_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('show_stats', sa.Boolean(), nullable=True),
    sa.Column('show_financial', sa.Boolean(), nullable=True),
    sa.Column('show_requirements', sa.Boolean(), nullable=True),
    sa.Column('show_image_gallery', sa.Boolean(), nullable=True),
    sa.Column('show_video', sa.Boolean(), nullable=True),
    sa.Column('show_extended_info', sa.Boolean(), nullable=True),
    sa.Column('custom_tagline', sa.String(length=200), nullable=True),
    sa.Column('custom_description', sa.Text(), nullable=True),
    sa.Column('extended_description', sa.Text(), nullable=True),
    sa.Column('layout_style', sa.String(length=50), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_display_settings_entity')
    )
    op.create_index(op.f('ix_display_settings_entity_id'), 'display_settings', ['entity_id'], unique=False)
    op.create_index(op.f('ix_display_settings_entity_type'), 'display_settings', ['entity_type'], unique=False)
    op.create_index(op.f('ix_display_settings_id'), 'display_settings', ['id'], unique=False)
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipeds_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('control_type', sa.Enum('PUBLIC', 'PRIVATE_NONPROFIT', 'PRIVATE_FOR_PROFIT', name='controltype'), nullable=False),
    sa.Column('primary_image_url', sa.String(length=500), nullable=True),
    sa.Column('student_faculty_ratio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('size_category', sa.String(length=50), nullable=True),
    sa.Column('locale', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_city'), 'institutions', ['city'], unique=False)
    op.create_index(op.f('ix_institutions_id'), 'institutions', ['id'], unique=False)
    op.create_index(op.f('ix_institutions_ipeds_id'), 'institutions', ['ipeds_id'], unique=True)
    op.create_index(op.f('ix_institutions_name'), 'institutions', ['name'], unique=False)
    op.create_index(op.f('ix_institutions_state'), 'institutions', ['state'], unique=False)
    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('scholarship_type', sa.Enum('ACADEMIC_MERIT', 'NEED_BASED', 'STEM', 'ARTS', 'DIVERSITY', 'ATHLETIC', 'LEADERSHIP', 'MILITARY', 'CAREER_SPECIFIC', name='scholarshiptype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', name='scholarshipstatus'), nullable=False),
    sa.Column('difficulty_level', sa.Enum('EASY', 'MODERATE', 'HARD', 'VERY_HARD', name='difficultylevel'), nullable=False),
    sa.Column('amount_min', sa.Integer(), nullable=False),
    sa.Column('amount_max', sa.Integer(), nullable=False),
    sa.Column('is_renewable', sa.Boolean(), nullable=False),
    sa.Column('number_of_awards', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('application_opens', sa.Date(), nullable=True),
    sa.Column('for_academic_year', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('min_gpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('primary_image_url', sa.String(length=500), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('applications_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarships_id'), 'scholarships', ['id'], unique=False)
    op.create_index(op.f('ix_scholarships_organization'), 'scholarships', ['organization'], unique=False)
    op.create_index(op.f('ix_scholarships_title'), 'scholarships', ['title'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('plan_tier', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('trial_end_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('current_period_start', sa.TIMESTAMP(), nullable=True),
    sa.Column('current_period_end', sa.TIMESTAMP(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_scholarships_title'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_organization'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_id'), table_name='scholarships')
    op.drop_table('scholarships')
    op.drop_index(op.f('ix_institutions_state'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_name'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_ipeds_id'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_id'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_city'), table_name='institutions')
    op.drop_table('institutions')
    op.drop_index(op.f('ix_display_settings_id'), table_name='display_settings')
    op.drop_index(op.f('ix_display_settings_entity_type'), table_name='display_settings')
    op.drop_index(op.f('ix_display_settings_entity_id'), table_name='display_settings')
    op.drop_table('display_settings')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
